<?php
$today=date('Y-m-d H:i:s', time()+60*60*-1);

$nilai=str_replace(".","",$_POST['maksimum_kredit']);
$tanah=str_replace(".","",$_POST['harga_tanah']);
$bangunan=str_replace(".","",$_POST['harga_bangunan']);
$tanah_imb=str_replace(".","",$_POST['harga_tanah_imb']);
$bangunan_imb=str_replace(".","",$_POST['harga_bangunan_imb']);
$ht=str_replace(".","",$_POST['nilai_ht']);



$LNC				=	$_POST['LNC'];
$NOAPLIKASI			=	$_POST['NOAPLIKASI'];
$NAMADEBITUR		=	$_POST['NAMADEBITUR'];
$TEMPATLAHIR		=	$_POST['TEMPATLAHIR'];
$TGLLAHIR			=	$_POST['TGLLAHIR'];
$CIF				=	$_POST['CIF'];
$no_rekg_pinjaman	=	$_POST['no_rekg_pinjaman'];
$afiliasi			=	$_POST['afiliasi'];
$instansi			=	$_POST['instansi'];
$produk				=	$_POST['produk'];
$maksimum_kredit	=	$nilai;
$no_pk				=	$_POST['no_pk'];
$tgl_pk				=	$_POST['tgl_pk'];
$jkw_kredit			=	$_POST['jkw_kredit'];
$fixed_rate			=	$_POST['fixed_rate'];
$tgl_jt_pk			=	$_POST['tgl_jt_pk'];
$tgl_jt_fixed_rate	=	$_POST['tgl_jt_fixed_rate'];
$lokasi_dokumen_asli	=	$_POST['lokasi_dokumen_asli'];
$amplop_asli			=	$_POST['amplop_asli'];
$amplopasli				=	$_POST['amplopasli'];
$lokasi_dokumen_copy	=	$_POST['lokasi_dokumen_copy'];
$amplop_copy			=	$_POST['amplop_copy'];
$amplopcopy				=	$_POST['amplopcopy'];
$jaminan				=	$_POST['jaminan'];
$jml_jaminan			=	$_POST['jml_jaminan'];
$jenis_surat_tanah		=	$_POST['jenis_surat_tanah'];
$alamat_collateral		=	$_POST['alamat_collateral'];
$luas_tanah				=	$_POST['luas_tanah'];
$tgl_jt_surat_tanah		=	$_POST['tgl_jt_surat_tanah'];
$jenis_pengikatan		=	$_POST['jenis_pengikatan'];
$nilai_ht				=	$ht;
$jkw_covernote			=	$_POST['jkw_covernote'];
$notaris				=	$_POST['notaris'];
$appraisal				=	$_POST['appraisal'];
$no_ajb					=	$_POST['no_ajb'];
$no_surat_tanah			=	$_POST['no_surat_tanah'];
$collateral_zipcode		=	$_POST['collateral_zipcode'];
$luas_bangunan			=	$_POST['luas_bangunan'];
$nilai_taksasi			=	$_POST['nilai_taksasi'];
$harga_tanah			=	$tanah;
$harga_bangunan			=	$bangunan;
$harga_tanah_imb		=	$tanah_imb;
$harga_bangunan_imb		=	$bangunan_imb;
$no_pengikatan			=	$_POST['no_pengikatan'];
$tgl_covernote			=	$_POST['tgl_covernote'];
$tgl_jt_covernote		=	$_POST['tgl_jt_covernote'];
$developer				=	$_POST['developer'];
$skim_pks				=	$_POST['skim_pks'];
$no_imb					=	$_POST['no_imb'];
$status_imb				=	$_POST['status_imb'];
$nama_perumahan			=	$_POST['nama_perumahan'];
$asuransi_jiwa			=	$_POST['asuransi_jiwa'];
$no_polis_ass_jiwa		=	$_POST['no_polis_ass_jiwa'];
$premi_jiwa				=	$_POST['premi_jiwa'];
$nilai_pertanggungan_ass_jiwa	=	$_POST['nilai_pertanggungan_ass_jiwa'];
$tgl_ass_jiwa					=	$_POST['tgl_ass_jiwa'];
$tgl_jt_ass_jiwa				=	$_POST['tgl_jt_ass_jiwa'];
$asuransi_kerugian				=	$_POST['asuransi_kerugian'];
$no_polis_ass_kerugian			=	$_POST['no_polis_ass_kerugian'];
$premi_kerugian					=	$_POST['premi_kerugian'];
$nilai_pertanggungan_ass_kerugian	=	$_POST['nilai_pertanggungan_ass_kerugian'];
$tgl_ass_kerugian					=	$_POST['tgl_ass_kerugian'];
$tgl_jt_ass_kerugian				=	$_POST['tgl_jt_ass_kerugian'];
$jenis_kendaraan					=	$_POST['jenis_kendaraan'];
$no_bpkb							=	$_POST['no_bpkb'];
$no_rangka							=	$_POST['no_rangka'];
$nama_dealer						=	$_POST['nama_dealer'];
$merk								=	$_POST['merk'];
$no_mesin							=	$_POST['no_mesin'];
$no_polisi							=	$_POST['no_polisi'];
$status_rekg						=	$_POST['status_rekg'];
$tgl_pelunasan						=	$_POST['tgl_pelunasan'];
$memo								=	$_POST['memo'];
$skdr								=	$_POST['skdr'];
$siup								=	$_POST['siup'];
$tdp								=	$_POST['tdp'];
$others								=	$_POST['others'];
$serah								=	$_POST['serah'];
$kendala							=	$_POST['kendala'];
$tgl_update							=	$_POST['tgl_update'];
$bunga								=	$_POST['bunga'];
$program							=	$_POST['program'];
$agama								=	$_POST['agama'];
$npwp								=	$_POST['npwp'];
$kelamin							=	$_POST['kelamin'];
$tgl_imb							=	$_POST['tgl_imb'];
$penilai							=	$_POST['penilai'];
$tgl_taksasi						=	$_POST['tgl_taksasi'];
$tinggal							=	$_POST['tinggal'];
$cabang								=	$_POST['cabang'];
$no_ktp								=	$_POST['no_ktp'];
$ibu_kandung						=	$_POST['ibu_kandung'];
$jabatan							=	$_POST['jabatan'];
$memo_appraisal						=	$_POST['memo_appraisal'];
$plafond_dimohon					=	$_POST['plafond_dimohon'];
$nama_emergency						=	$_POST['nama_emergency'];
$telp_emergency						=	$_POST['telp_emergency'];
$alamat_kantor						=	$_POST['alamat_kantor'];
$hubungan							=	$_POST['hubungan'];
$progress							=	$_POST['progress'];

Include ("koneksi.php");
mysql_select_db("collateral_db");

$ubah="UPDATE debitur SET 
LNC					=	'$LNC',
NOAPLIKASI			=	'$NOAPLIKASI',
NAMADEBITUR			=	'$NAMADEBITUR',
TEMPATLAHIR			=	'$TEMPATLAHIR',
TGLLAHIR			=	'$TGLLAHIR',
CIF					=	'$CIF',
no_rekg_pinjaman	=	'$no_rekg_pinjaman',
afiliasi			=	'$afiliasi',
instansi			=	'$instansi',
produk				=	'$produk',
maksimum_kredit		=	'$maksimum_kredit',
no_pk				=	'$no_pk',
tgl_pk				=	'$tgl_pk',
jkw_kredit			=	'$jkw_kredit',
fixed_rate			=	'$fixed_rate',
tgl_jt_pk			=	'$tgl_jt_pk',
tgl_jt_fixed_rate	=	'$tgl_jt_fixed_rate',
lokasi_dokumen_asli	=	'$lokasi_dokumen_asli',
amplop_asli			=	'$amplop_asli',
amplopasli			=	'$amplopasli',
lokasi_dokumen_copy	=	'$lokasi_dokumen_copy',
amplop_copy			=	'$amplop_copy',
amplopcopy			=	'$amplopcopy',
jaminan				=	'$jaminan',
jml_jaminan			=	'$jml_jaminan',
jenis_surat_tanah	=	'$jenis_surat_tanah',
alamat_collateral	=	'$alamat_collateral',
luas_tanah			=	'$luas_tanah',
tgl_jt_surat_tanah	=	'$tgl_jt_surat_tanah',
jenis_pengikatan	=	'$jenis_pengikatan',
nilai_ht			=	'$nilai_ht',
jkw_covernote		=	'$jkw_covernote',
notaris				=	'$notaris',
appraisal			=	'$appraisal',
no_ajb				=	'$no_ajb',
no_surat_tanah		=	'$no_surat_tanah',
collateral_zipcode	=	'$collateral_zipcode',
luas_bangunan		=	'$luas_bangunan',
nilai_taksasi		=	'$nilai_taksasi',
harga_tanah			=	'$harga_tanah',
harga_bangunan		=	'$harga_bangunan',
harga_tanah_imb		=	'$harga_tanah_imb',
harga_bangunan_imb	=	'$harga_bangunan_imb',
no_pengikatan		=	'$no_pengikatan',
tgl_covernote		=	'$tgl_covernote',
tgl_jt_covernote	=	'$tgl_jt_covernote',
developer			=	'$developer',
skim_pks			=	'$skim_pks',
no_imb				=	'$no_imb',
status_imb			=	'$status_imb',
nama_perumahan		=	'$nama_perumahan',
asuransi_jiwa		=	'$asuransi_jiwa',
no_polis_ass_jiwa	=	'$no_polis_ass_jiwa',
premi_jiwa			=	'$premi_jiwa',
nilai_pertanggungan_ass_jiwa	=	'$nilai_pertanggungan_ass_jiwa',
tgl_ass_jiwa					=	'$tgl_ass_jiwa',
tgl_jt_ass_jiwa					=	'$tgl_jt_ass_jiwa',
asuransi_kerugian				=	'$asuransi_kerugian',
no_polis_ass_kerugian			=	'$no_polis_ass_kerugian',
premi_kerugian					=	'$premi_kerugian',
nilai_pertanggungan_ass_kerugian	=	'$nilai_pertanggungan_ass_kerugian',
tgl_ass_kerugian					=	'$tgl_ass_kerugian',
tgl_jt_ass_kerugian					=	'$tgl_jt_ass_kerugian',
jenis_kendaraan						=	'$jenis_kendaraan',
no_bpkb								=	'$no_bpkb',
no_rangka							=	'$no_rangka',
nama_dealer							=	'$nama_dealer',
merk								=	'$merk',
no_mesin							=	'$no_mesin',
no_polisi							=	'$no_polisi',
status_rekg							=	'$status_rekg',
tgl_pelunasan						=	'$tgl_pelunasan',
memo								=	'$memo',
skdr								=	'$skdr',
siup								=	'$siup',
tdp									=	'$tdp',
others								=	'$others',
serah								=	'$serah',
kendala								=	'$kendala',
tgl_update							=	'$today',
bunga								=	'$bunga',
program								=	'$program',
agama								=	'$agama',
npwp								=	'$npwp',
kelamin								=	'$kelamin',
tgl_imb								=	'$tgl_imb',
penilai								=	'$penilai',
tgl_taksasi							=	'$tgl_taksasi',
tinggal								=	'$tinggal',
cabang								=	'$cabang',
no_ktp								=   '$no_ktp',
ibu_kandung							=   '$ibu_kandung',
jabatan								=   '$jabatan',
memo_appraisal						=   '$memo_appraisal',
plafond_dimohon						=   '$plafond_dimohon',
nama_emergency						=   '$nama_emergency',
telp_emergency						=   '$telp_emergency',
alamat_kantor						=   '$alamat_kantor',
hubungan							=   '$hubungan',
progress							=   '$progress'


WHERE no_rekg_pinjaman='$_POST[id]'"; 

$hsl=mysql_query ($ubah);

echo ("<br><a href=summary.php><b>MENU UTAMA</a>&nbsp&nbsp&nbsp<a href=cads_menu.htm>CADS MENU</a>&nbsp&nbsp&nbsp
<a href=menu_laporan.htm>REPORTING</a></b><br><br><br><br>");
if ($hsl) echo ("<p><b>Proses Update Data Sukses !!! </b></p>");
else echo ("<p><b>Update Data Gagal !!! </b></p>");
?>